# Generated by Django 2.0.6 on 2018-08-17 15:52

import apps.annuaire.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('memberid', models.AutoField(primary_key=True, serialize=False)),
                ('firstname', models.CharField(max_length=30, verbose_name='prénom')),
                ('lastname', models.CharField(max_length=30, verbose_name='nom')),
                ('registration_date', models.DateField(default=django.utils.timezone.now, verbose_name="date d'inscription")),
                ('expiration_date', models.DateField(default=apps.annuaire.models.one_year_delta, verbose_name="date d'expiration")),
            ],
            options={
                'verbose_name': 'membre',
                'ordering': ('lastname', 'firstname'),
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.IntegerField(blank=True, choices=[(0, 'Homme'), (1, 'Femme')], null=True, verbose_name='sexe')),
                ('photo', models.ImageField(blank=True, null=True, upload_to=apps.annuaire.models.avatar_directory_path)),
                ('city', models.CharField(blank=True, max_length=500, null=True, verbose_name='ville')),
                ('region', models.CharField(blank=True, max_length=500, null=True, verbose_name='region')),
                ('country', models.CharField(blank=True, max_length=500, null=True, verbose_name='pays')),
                ('bio', models.TextField(blank=True, max_length=500, null=True, verbose_name='biographie')),
                ('promo', models.IntegerField(blank=True, null=True, verbose_name='promotion')),
                ('gap_year', models.BooleanField(default=False, verbose_name='césure')),
                ('miscellaneous', models.TextField(blank=True, max_length=500, verbose_name='divers')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='member',
            name='profile',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='annuaire.Profile'),
        ),
    ]
