# Generated by Django 2.0.6 on 2018-06-23 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annuaire', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='promo',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
