# Generated by Django 2.0.6 on 2018-06-23 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annuaire', '0002_auto_20180623_1648'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='gapYear',
            field=models.BooleanField(default=False),
        ),
    ]
