# Generated by Django 2.0.6 on 2018-06-23 16:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('annuaire', '0003_auto_20180623_1649'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='gapYear',
            new_name='gap_year',
        ),
    ]
