# Generated by Django 2.0.6 on 2018-06-24 16:59

import apps.annuaire.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annuaire', '0004_auto_20180623_1859'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='photo',
            field=models.ImageField(blank=True, upload_to=apps.annuaire.models.avatar_directory_path),
        ),
    ]
