# Generated by Django 2.0.6 on 2018-06-24 17:01

import apps.annuaire.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annuaire', '0005_auto_20180624_1859'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to=apps.annuaire.models.avatar_directory_path),
        ),
    ]
