# Generated by Django 2.0.6 on 2018-07-07 20:19

import apps.annuaire.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('annuaire', '0006_auto_20180624_1901'),
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('memberid', models.AutoField(primary_key=True, serialize=False)),
                ('firstname', models.CharField(max_length=30)),
                ('lastname', models.CharField(max_length=30)),
                ('photo', models.ImageField(blank=True, null=True, upload_to=apps.annuaire.models.avatar_directory_path)),
                ('bio', models.TextField(max_length=500)),
                ('promo', models.IntegerField(null=True)),
                ('gap_year', models.BooleanField(default=False)),
            ],
        ),
        migrations.RemoveField(
            model_name='profile',
            name='bio',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='gap_year',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='photo',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='promo',
        ),
        migrations.AddField(
            model_name='profile',
            name='member',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, to='annuaire.Member'),
            preserve_default=False,
        ),
    ]
