# Generated by Django 2.0.6 on 2018-08-05 08:53

import apps.annuaire.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('annuaire', '0007_auto_20180707_2219'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='bio',
        ),
        migrations.RemoveField(
            model_name='member',
            name='gap_year',
        ),
        migrations.RemoveField(
            model_name='member',
            name='photo',
        ),
        migrations.RemoveField(
            model_name='member',
            name='promo',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='member',
        ),
        migrations.AddField(
            model_name='member',
            name='profile',
            field=models.OneToOneField(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, to='annuaire.Profile'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='bio',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='gap_year',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='miscellaneous',
            field=models.TextField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='profile',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to=apps.annuaire.models.avatar_directory_path),
        ),
        migrations.AddField(
            model_name='profile',
            name='promo',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
