# Generated by Django 2.0.6 on 2018-08-05 09:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('annuaire', '0008_auto_20180805_1053'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='profile',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='annuaire.Profile'),
        ),
    ]
