# Generated by Django 2.0.6 on 2018-08-07 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annuaire', '0011_auto_20180807_1717'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='city',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
