# Generated by Django 2.0.6 on 2018-08-13 07:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('annuaire', '0012_profile_city'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='profile',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='annuaire.Profile'),
        ),
    ]
