# Generated by Django 2.0.6 on 2018-08-13 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annuaire', '0013_auto_20180813_0922'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='gender',
            field=models.IntegerField(choices=[(0, 'Male'), (1, 'Female')], default=0),
            preserve_default=False,
        ),
    ]
