# Generated by Django 2.0.6 on 2018-08-14 06:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annuaire', '0015_auto_20180813_0936'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='expiration_date',
            field=models.DateField(default=datetime.date(2019, 8, 14)),
        ),
        migrations.AddField(
            model_name='member',
            name='registration_date',
            field=models.DateField(default=datetime.date(2018, 8, 14)),
        ),
        migrations.AlterField(
            model_name='profile',
            name='gender',
            field=models.IntegerField(blank=True, choices=[(0, 'Homme'), (1, 'Femme')], null=True),
        ),
    ]
