# Generated by Django 2.0.6 on 2018-08-14 06:37

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('annuaire', '0016_auto_20180814_0833'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='expiration_date',
            field=models.DateField(default=datetime.datetime(2019, 8, 14, 6, 37, 46, 584021, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='member',
            name='registration_date',
            field=models.DateField(default=datetime.datetime(2018, 8, 14, 6, 37, 46, 583993, tzinfo=utc)),
        ),
    ]
