# Generated by Django 2.0.6 on 2018-08-14 07:06

import apps.annuaire.models
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('annuaire', '0017_auto_20180814_0837'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='expiration_date',
            field=models.DateField(default=apps.annuaire.models.one_year_delta),
        ),
        migrations.AlterField(
            model_name='member',
            name='registration_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
